### ISSUE TITLE
All relevant feature or minimal set feature selection?

### ISSUE THREAD

**Issue by rictoo** [predict-idlab/powershap#44]
Hey all, I know Boruta is an "All relevant feature selection" method vs. e.g., mRMR which aims to find a minimum optimum set of features. This is described [here](https://www.sciencedirect.com/science/article/pii/S0020025520302048).

I'm just wondering if Powershap is an all relevant feature selection method or a minimum optimum set feature selection method? Thanks!

**Comment by JarneVerhaeghe** [comment]
Hi @rictoo! 

We discussed this a bit in our powershap paper. Powershap is built on comparing every feature to a random feature to determine whether it is informative. Therefore the design idea is the "All relevant feature selection" such as Boruta. However, because we use a wrapper method and therefore train a model, the final feature subset is susceptible to feature interactions which could result in a smaller subset of features that are optimal enough for the model. If you are fully interested in all relevant features, we advise you to use the _force_convergence_ mode of Powershap. So concluding: A single powershap execution will be a combination of the minimum optimum set and all relevant features, while a _force_converge_ will try to find all relevant features.

I hope this answers your question?
